version: '2'

services:
    producer:
        image: producer
        network_mode: "host"
        volumes:
          - "/dev/shm:/dev/shm"
        privileged: true
        ulimits:
          memlock:
            soft: 4000000
            hard: 4000000
        command: "
               --camera=/dev/video0 \
               --cid=111 \
               --name=camera0 \
               --width=1280 \
               --height=720 \
               --bpp=24 \
               --freq=5"
    
    consumer:
        image: consumer
        depends_on:
          - producer
        restart: always
        network_mode: "host"
        working_dir: /opt/
        volumes:
          - "/dev/shm:/dev/shm"
          - .:/opt/
          - /tmp/.X11-unix:/tmp/.X11-unix
        environment: 
          - DISPLAY=$DISPLAY
        privileged: true
        ulimits:
          memlock:
            soft: 4000000
            hard: 4000000
        command: "
               --cid=111 \
               --name=camera0 \
               --width=1280 \
               --height=720 \
               --bpp=24 \
               --blurkernelsize=3 \
               --adapthreshkernelsize=5 \
               --adapthreshconst=2 \
               --cannythreshold=20 \
               --houghthreshold=100 \
               --linediff=2.1f \
               --onelinediff=5.0f \
               --horisontallimit=12.0f \
               --memthreshold=0.5 \
               --lowerlanelimit=200 \
               --upperlanelimit=500 \
               --roix=200 \
               --roiy=170 \
               --roiwidth=800 \
               --roiheight=400 \
               --verbose"
